### ISSUE TITLE
Usage in README.md doesn't work

### ISSUE THREAD

**Issue by ThibaultDewailly** [barnumbirr/action-forge-publish#3]
Thanks for this work :)

When using the step : 

    - name: Get latest tag
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

workflow returns and error : 
The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

This can be fixed by using ::set-output instead of ::set-env to not allow it explicitely

For instance : 

    - name: Get latest tag
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Clone repository
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.vars.outputs.tag }}

**Comment by barnumbirr** [comment]
Hello,

nice catch! Haven't use this action in a couple of months so I didn't see the depreciation warning.
Would you mind creating a PR for this?

Cheers.

**Comment by ThibaultDewailly** [comment]
Sure ! Here it is : 

https://github.com/barnumbirr/action-forge-publish/pull/4

**Comment by barnumbirr** [comment]
Merged! Thanks a lot for your contribution. 🎉
