### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Enucatl** [barnumbirr/action-forge-publish#5]
Hi, I can't seem to build [my package](https://github.com/Enucatl/i2pd/blob/main/.github/workflows/main.yml) on github, while it works locally. The only difference is the ruby version (2.5.9 vs 3.1.0 on github):

```
Run barnumbirr/action-forge-publish@v2.9.0
  with:
    REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
  env:
    FORGE_API_KEY: ***
    REPOSITORY_URL: https://forgeapi.puppet.com/v3/releases
/usr/bin/docker run --name bef191f9b0737477187dd9a16b709faf1_2d093a --label 94859b --workdir /github/workspace --rm -e FORGE_API_KEY -e REPOSITORY_URL -e INPUT_FORGE_API_KEY -e INPUT_REPOSITORY_URL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_TRIGGERING_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/i2pd/i2pd":"/github/workspace" 94859b:ef191f9b0737477187dd9a16b709faf1
/usr/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/lib/pdk/analytics/client/noop.rb:13:in `screen_view': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/lib/pdk/cli/util.rb:300:in `analytics_screen_view'
	from /usr/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/lib/pdk/cli/build.rb:24:in `block (2 levels) in <module:CLI>'
	from /usr/lib/ruby/gems/3.1.0/gems/cri-2.15.11/lib/cri/command.rb:362:in `run_this'
	from /usr/lib/ruby/gems/3.1.0/gems/cri-2.15.11/lib/cri/command.rb:298:in `run'
	from /usr/lib/ruby/gems/3.1.0/gems/cri-2.15.11/lib/cri/command.rb:316:in `run'
	from /usr/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/lib/pdk/cli.rb:71:in `run'
	from /usr/lib/ruby/gems/3.1.0/gems/pdk-2.5.0/exe/pdk:6:in `<top (required)>'
	from /usr/bin/pdk:25:in `load'
	from /usr/bin/pdk:25:in `<main>'
```

**Comment by barnumbirr** [comment]
Hey,

nice catch 💪
Seems [this is an upstream issue](https://github.com/puppetlabs/pdk/issues/1171) that would point to `pdk` not being compatible with `Ruby 3+`. Guess the quick fix is to revert to [`Alpine 3.14`, which seems to be the last version to include `Ruby 2`](https://pkgs.alpinelinux.org/packages?name=ruby&branch=v3.14&repo=&arch=&maintainer=).
What do you think?

Cheers.

**Comment by Enucatl** [comment]
I think it may be the best solution. That issue has been open for 4 months now, with no response from anyone. I guess puppet is busy with being acquired.

**Comment by barnumbirr** [comment]
I've just released [v2.9.1](https://github.com/barnumbirr/action-forge-publish/releases/tag/v2.9.1) which should hopefully fix the issue.

**Comment by barnumbirr** [comment]
@Enucatl Looking at `alpine-pdk` history, I just realized that both `libffi-dev ` and `ruby-io-console` used to be required dependencies, Can you confirm that  [v2.9.1](https://github.com/barnumbirr/action-forge-publish/releases/tag/v2.9.1) of the avtion works as expected?

**EDIT:** found the answer: https://github.com/Enucatl/i2pd/runs/8021451935?check_suite_focus=true
I'll release a fix for the fix ASAP. My apologies for the mess.

**Comment by Enucatl** [comment]
Indeed, see #6

**Comment by barnumbirr** [comment]
Fixed in 101636eb063c3c2e9c6b6a08832e6d811287e8c6 and v2.9.2.

**Comment by Enucatl** [comment]
that's great, thanks for the amazingly fast response!

**Comment by barnumbirr** [comment]
No worries.
Thanks again for reporting the issue and my apologies again for the mixup.
